### ISSUE TITLE
堆内存heapdump分析出错

### ISSUE THREAD

**Issue by royalrover** [hyj1991/v8-cpu-analysis#6]
```
const fs = require('fs');
const v8Analytics = require('v8-analytics');

//list you heap memory info
const json = JSON.parse(fs.readFileSync('./heapdump-62589-20180306-110206.heapsnapshot'));
const {leakPoint, heapMap, statistics} = v8Analytics.memAnalytics(json)

console.log(leakPoint,heapMap)
```
stack: 
```
let nodeDetail = nodes.slice(index * nodeFieldCount, index * nodeFieldCount + nodeFieldCount);
                                       ^

TypeError: Cannot convert a Symbol value to a number
    at heapNodeSerialize (/Users/young/github/Npids/node_modules/v8-analytics/lib/mem_analysis.js:142:40)
    at Object.get (/Users/young/github/Npids/node_modules/v8-analytics/lib/mem_analysis.js:210:40)
    at Object.get (/Users/young/github/Npids/node_modules/v8-analytics/lib/mem_analysis.js:219:26)
    at formatValue (util.js:423:37)
    at inspect (util.js:324:10)
    at format (util.js:191:12)
    at Console.log (console.js:130:21)
    at Object.<anonymous> (/Users/young/github/Npids/analyse/profiler.js:9:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

**Comment by hyj1991** [comment]
@royalrover 抱歉，精力所限，这个项目不维护了暂时

你要看自己 dump 的堆信息可以使用下免费的这个工具: [Node.js 性能平台](https://node.console.aliyun.com)
注册应用进入 **文件 -> 上传文件**，选择你的堆快照，可以查看自己堆快照的分析结果

**Comment by royalrover** [comment]
easy-monitor里面的mat分析是靠谱的吗？

**Comment by hyj1991** [comment]
@royalrover 还算靠谱吧 (不排除有问题，没有工具能做到百分百正确)，而且受 js 性能和 v8 堆和最大字符串长度的限制，不能对大堆进行分析。

**Comment by royalrover** [comment]
请教下，这个算法是mat吗，哪里可以参考下资料？请问可否给予联系方式，有事情请教，谢谢！

**Comment by hyj1991** [comment]
@royalrover 这里说一样，你有什么问题呢？

**Comment by royalrover** [comment]
内存泄漏分析算法

**Comment by hyj1991** [comment]
无非就是 dominator tree 的算法实现，google 下很多，包括 chrome devtools 里面的也是一样

你也可以自己写

**Comment by royalrover** [comment]
感谢！
